ALTER TABLE "Business"
ADD COLUMN "annualTurnover" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "fixedAssets" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "isProfessionalServices" BOOLEAN NOT NULL DEFAULT false;
